name: deploy-docker-image

env:
  TEST_TAG: jovermars/auth0-deploy-cli:test
  LATEST_TAG: jovermars/auth0-deploy-cli:latest

on: 
  schedule:
    - cron: '0 4 * * 5'
  push:
    branches:
      - main

jobs: 
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
